name: Build macOS App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
          pip install py2app

      - name: Build .app bundle
        run: |
          python setup.py py2app

      - name: Create DMG
        run: |
          mkdir -p dist_dmg
          hdiutil create -volname TemporalDenoiser \
                         -srcfolder dist/TemporalDenoiser.app \
                         -ov -format UDZO dist_dmg/TemporalDenoiser.dmg

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: TemporalDenoiser-macOS
          path: dist_dmg/*.dmg
